parameters:
#    presta_sonata_gedmo_doctrine_extensions.example.class: Presta\SonataGedmoDoctrineExtensionsBundle\Example

services:
#    presta_sonata_gedmo_doctrine_extensions.example:
#        class: %presta_sonata_gedmo_doctrine_extensions.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
